AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  textract_to_text

  Sample SAM Template for textract_to_text

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  TextractToTextFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: textract_to_text/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        TextractToText:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /textract_to_text
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TextractToTextApi:
    Description: "API Gateway endpoint URL for Prod stage for TextractToText function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/textract_to_text/"
  TextractToTextFunction:
    Description: "TextractToText Lambda Function ARN"
    Value: !GetAtt TextractToTextFunction.Arn
  TextractToTextFunctionIamRole:
    Description: "Implicit IAM Role created for TextractToText function"
    Value: !GetAtt TextractToTextFunctionRole.Arn
