version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sqstotextract"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-43n8l7q0ou5e"
s3_prefix = "sqstotextract"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
