AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sqs_to_textract

  Sample SAM Template for sqs_to_textract

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SQSToTextractFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: sqs_to_textract/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        SQSToTextract:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sqs_to_textract
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SQSToTextractApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sqs_to_textract/"
  SQSToTextractFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SQSToTextractFunction.Arn
  SQSToTextractFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SQSToTextractFunctionRole.Arn
